# Generated by Django 5.2.5 on 2025-08-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_book_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('fantasia', 'Fantasía'), ('ciencia_ficcion', 'Ciencia Ficción'), ('misterio', 'Misterio'), ('biografia', 'Biografía'), ('poesia', 'Poesía'), ('romance', 'Romance'), ('terror', 'Terror'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
